apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
namePrefix: example-
commonLabels:
  app: example-emqx

secretGenerator:
- name: emqx-certs
  files:
  - certs/cacert.pem
  - certs/cert.pem
  - certs/client-cert.pem
  - certs/client-key.pem 
  - certs/key.pem
  type: Opaque
  behavior: merge

configMapGenerator:
- name: emqx-env
  env: emqx.env
  behavior: merge

bases:
# -../../base 
- https://github.com/wuxingzhong/emqx-kustomize/base
patchesStrategicMerge:
- deployment.yaml
