#author: wuxingzhong
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: emqx
spec:
  serviceName: emqx-svc
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx   
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'sysctl -w fs.file-max=2097152; sysctl -w fs.nr_open=2097152; ulimit -n 1048576']
        securityContext:
          privileged: true 
      containers:
      - name: emqx
        image: emqx/emqx:v3.1-rc.3 
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 1883
        - name: ssl
          containerPort: 8883          
        - name: dashboard
          containerPort: 18083
        - name: http
          containerPort: 8080
        - name: ws
          containerPort: 8083
        - name: wss
          containerPort: 8084
        - name: coap
          containerPort: 5683
          protocol: UDP 
        - name: inner
          containerPort: 11883
        env:
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__AUTOCLEAN
          value: "30s"          
        - name: EMQX_LOADED_PLUGINS
          value: emqx_dashboard,emqx_management,emqx_rule_engine,emqx_auth_http
        - name: EMQX_AUTH__HTTP__AUTH_REQ
          valueFrom:
            configMapKeyRef:
              name: emqx-conf
              key: mqtt_auth_uri  
        - name: EMQX_AUTH__HTTP__AUTH_REQ__METHOD
          value: post
        - name: EMQX_AUTH__HTTP__AUTH_REQ__PARAMS
          value: ipaddress=%a,clientid=%c,username=%u,password=%P
        - name: EMQX_AUTH__HTTP__ACL_REQ
          valueFrom:
            configMapKeyRef:
              name: emqx-conf
              key: mqtt_acl_uri
        - name: EMQX_AUTH__HTTP__ACL_REQ__METHOD
          value: post
        - name: EMQX_AUTH__HTTP__ACL_REQ__PARAMS
          value: access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t
        - name: EMQX_LOG__CONSOLE
          value: console
        - name: EMQX_LOG__CONSOLE__LEVEL
          value: warning #debug  
        - name: EMQX_NODE__PROCESS_LIMIT
          value: "2097152"
        - name: EMQX_NODE__MAX_PORTS
          value: "1048576"
        - name: EMQX_LISTENER__TCP__EXTERNAL__MAX_CLIENTS
          value: "1000000"
        - name: EMQX_DASHBOARD__DEFAULT_USER__LOGIN
          value: "emqx_sw"
        - name: EMQX_DASHBOARD__DEFAULT_USER__PASSWORD
          value: "emqx_zg123456"
        - name: EMQX_MQTT__ALLOW_ANONYMOUS
          value: "false"
        - name: EMQX_MQTT__ACL_NOMATCH
          value: deny
        - name: EMQX_CLUSTER__NAME
          value: emqxcl
        - name: EMQX_CLUSTER__DISCOVERY
          value: "dns"
        - name: EMQX_CLUSTER__DNS__NAME
          valueFrom:
            configMapKeyRef:
              name: emqx-conf
              key: dns_name
        - name: EMQX_CLUSTER__DNS__APP
          value: "emqx"
        - name: EMQX_CLUSTER__AUTOHEAL
          value: "on"
        - name: EMQX_CLUSTER__AUTOCLEAN
          value: "5m"
        - name: EMQX_NODE__DIST_LISTEN_MIN
          value: "8930"
        - name: EMQX_NODE__DIST_LISTEN_MAX
          value: "8998"
        - name: EMQX_LISTENER__TCP__INTERNAL
          value: "11883"
        - name: TZ
          value: "Asia/Shanghai"
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 5
          periodSeconds: 10            
        volumeMounts:    
        - name: emqx-certs
          mountPath: /opt/emqttd/etc/certs/
          readOnly: true
        resources:
          requests:
            memory: "1024Mi"
            cpu: "600m"
          limits:
            memory: "3096Mi"
            cpu: "1800m" 
      dnsConfig:
        options:
        - name: timeout
          value: "2"
        - name: attempts
          value: "3"
        - name: single-request-reopen                               
      volumes:
        - name: emqx-certs
          secret:
            secretName: emqx-certs
            defaultMode: 0777
      restartPolicy: Always
      imagePullSecrets:
      - name: docker.sunniwell.net
  volumeClaimTemplates: []